### ISSUE TITLE
After latest commit getting : AttributeError: module 'gabriel_server.local_engine' has no attribute 'run'

### ISSUE THREAD

**Issue by ak89224** [cmusatyalab/openrtist#19]
root@master240:~# docker run -it --name openrtis1 --entrypoint=bash cmusatyalab/openrtist
root@e62cdb9f544b:/openrtist/server# ll
total 64
drwxr-xr-x  2 root root 4096 Jun  8 04:35 ./
drwxr-xr-x 10 root root 4096 Jun  8 04:38 ../
-rw-r--r--  1 root root   52 Jun  8 04:35 docker-compose.override.yml
-rw-r--r--  1 root root  673 Jun  8 04:35 docker-compose.yml
-rwxr-xr-x  1 root root   80 Jun  8 04:35 entrypoint.sh*
-rwxr-xr-x  1 root root 4057 Jun  8 04:35 main.py*
-rw-r--r--  1 root root 1603 Jun  8 04:35 openrtist_adapter.py
-rw-r--r--  1 root root 4942 Jun  8 04:35 openrtist_engine.py
lrwxrwxrwx  1 root root   11 Jun  8 04:35 openrtist_protocol -> ../protocol/
-rw-r--r--  1 root root 6664 Jun  8 04:35 openvino_adapter.py
-rw-r--r--  1 root root   77 Jun  8 04:35 requirements.txt
-rw-r--r--  1 root root 1440 Jun  8 04:35 timing_engine.py
-rw-r--r--  1 root root 3447 Jun  8 04:35 torch_adapter.py
-rw-r--r--  1 root root 5444 Jun  8 04:35 transformer_net.py
root@e62cdb9f544b:/openrtist/server# sh entrypoint.sh
```
entrypoint.sh: 3: entrypoint.sh: source: not found
Traceback (most recent call last):
  File "./main.py", line 137, in <module>
    main()
  File "./main.py", line 127, in main
    local_engine.run(
AttributeError: module 'gabriel_server.local_engine' has no attribute 'run'
```
```
root@master240:~# docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:27:18 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:26:20 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
```
root@master240:~# nvidia-smi
Tue Jun  9 05:03:25 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P620         Off  | 00000000:3B:00.0 Off |                  N/A |
| 34%   25C    P8    N/A /  N/A |      0MiB /  2000MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by rogerthat94** [comment]
Sorry about this issue. Would you mind running `docker pull cmusatyalab/openrtist:ht_improvements` and then trying this version of the container?

**Comment by ak89224** [comment]
@rogerthat94 ,
Thanks man ! It worked.

**Comment by rogerthat94** [comment]
No problem! I'll make sure to get better about developing on branches and tagging builds on Docker hub.
