### ISSUE TITLE
Problem connecting to server on AWS

### ISSUE THREAD

**Issue by jblakley** [cmusatyalab/openrtist#3]
Having an issue getting the OpenRTiST server running AWS. Get everything set up and running but when I connect the client, getting a python error. Using latest Deep Learning Ubuntu AMI (9.0). The AMI referenced in the documentation is no longer available.

Any ideas?

INFO     --------------------------------------------------
INFO     User communication module is connected
INFO     New offloading engine connected to video stream
INFO     Mobile client is connected for (Mobile Video Server)
INFO     Mobile client is connected for (Mobile Result Server)
WARNING  connection closed not gracefully (Mobile Result Server): 'utf8' codec can't decode byte 0xff in position 0: invalid start byte

WARNING  Traceback (most recent call last):
  File "/workspace/gabriel/server/bin/../gabriel/common/network/TCP.py", line 91, in handle
    self._handle_queue_data()
  File "/workspace/gabriel/server/bin/../gabriel/control/mobile_server.py", line 381, in _handle_queue_data
    rtn_header=json.dumps(rtn_header_json)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte

INFO     [TERMINATE] Finish Mobile Result Server

**Comment by teiszler** [comment]
@jblakley,
 I venture you have run the gabriel-control without the legacy flag (-l) and then attempted to connect the legacy Android client to it.  There are slight differences in the protocols between the legacy and non-legacy applications and this is likely the error you are seeing. If you were to launch the python OpenRTiST client, which uses the newer protocol, you probably would not see any issue. Stop the proxy, gabriel-ucomm, and gabriel-control and ensure you relaunch the control with the -l flag.

Regards,
Tom

**Comment by jblakley** [comment]
I verified I was running with the -l option. And, stopped and restarted several times control, ucomm and proxy -- still same thing. I also tried running without the -l option and the Android client app just crashed when it connected to server.

**Comment by teiszler** [comment]
Yeah, you can't connect the Android client to gabriel-control unless you have the -l option. One other data point you could test, is whether or not you can get the Python client to connect to gabriel-control without the -l flag. If this also doesn't work, then it must be something else. I will try to setup the same environment in AWS and see if I run into the same issue.

**Comment by teiszler** [comment]
I set OpenRTiST up on EC2 Oregon using the same Deep Learning 9.0 image you mentioned. I was able to connect to it without issue (though it did install a newer version of docker-ce than nvidia-docker requires so I had to manually downgrade it). 

Did you start the proper proxy.py (i.e. the one in /workspace/gabriel/server/openrtist/openrtist_android) for connecting Android clients? If you started this one that resides in openrtist_python this could by why there is a mismatch in decoding the data sent from the client.

**Comment by teiszler** [comment]
@jblakley,

I also verified that the image in the README (ami-041db87c) is still available. It is no longer listed in the Quick Start set of images when you go to launch an instance, but if you go to the 'Community AMIs' tab and search for that ami ID, you can then select that image to launch. 

Regards,
Tom

**Comment by jblakley** [comment]
Aha! That's it -- you solved it! I had started the proxy from /workspace/gabriel/server/openrtist/openrtist_python rather than from /workspace/gabriel/server/openrtist/openrtist_android.

Its working great now with the Deep Learning 9.0 image.

Thanks, Tom!!!
