### ISSUE TITLE
Decrease the size of the original image

### ISSUE THREAD

**Issue by junjuew** [cmusatyalab/openrtist#6]
The size of the original image looks too big on the 9th floor display.

**Comment by teiszler** [comment]
I am thinking we should homogenize the resolution of original image files rather than try to do some scaling from within the client.

**Comment by teiszler** [comment]
Fixed with https://github.com/cmusatyalab/openrtist/commit/fb968cd7bca80a71aaa4750779c33d7a9f9960ab
